services:
  symfony:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_API_URL=http://host.docker.internal:5050
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: php -S 0.0.0.0:8000 -t public
